# Generated by Django 5.0.6 on 2024-06-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
